### ISSUE TITLE
Just not working on linux?

### ISSUE THREAD

**Issue by diaevd** [rustlang-cn/Rust-webapp-starter#1]
Hi!

build for project is ok.

```
$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2018-04-27-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (overridden by '/home/diabolo/src/rust/Rust-webapp-starter/rust-toolchain')
rustc 1.30.0 (da5f414c2 2018-10-24)
```

But with cargo run is panics:

```
thread 'arbiter:eecef5a7-85b4-4d4e-9c1d-4507bdb1e477:actix-net-worker-6' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

stack backtrace:
   0:     0x561b4e50dcb5 - backtrace::backtrace::libunwind::trace::h1be80d204973f767
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hc2cd1a4a754271e5
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x561b4e50844e - backtrace::capture::Backtrace::new_unresolved::h910583233dba78c1
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x561b4e506ba3 - failure::backtrace::internal::InternalBacktrace::new::h07f638dba2cc023e
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/backtrace/internal.rs:44
   3:     0x561b4e50626c - failure::backtrace::Backtrace::new::h41bc7e46b32902f0
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/backtrace/mod.rs:111
   4:     0x561b4e02965d - <actix_web::error::Error as core::convert::From<T>>::from::hbca4f12a8f670185
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/error.rs:171
   5:     0x561b4de9bcf0 - <actix_web::fs::StaticFiles<S, C>>::with_config_pool::hdadafc7d858cc69c
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/fs.rs:683
   6:     0x561b4de9baae - <actix_web::fs::StaticFiles<S, C>>::with_config::hfc27d3c0035de3bf
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/fs.rs:675
   7:     0x561b4de9a0a4 - <actix_web::fs::StaticFiles<S>>::new::heca14dbc2592e46c
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/fs.rs:653
   8:     0x561b4dd90cf0 - Rust_webapp_starter::router::app::h656d31ac519c0ae6
                        at src/router.rs:36
   9:     0x561b4de51873 - Rust_webapp_starter::main::{{closure}}::h6c0bbdb1a0cd1d7d
                        at src/main.rs:35
  10:     0x561b4dd37589 - <actix_web::server::builder::HttpServiceBuilder<F, H, A>>::finish::{{closure}}::ha3d1b0914769e376
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.7.13/src/server/builder.rs:52
  11:     0x561b4dd373d9 - <F as actix_net::server::services::ServiceFactory>::create::h6a488d8a2511c9f0
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/server/services.rs:241
  12:     0x561b4df1e2ae - <actix_net::server::services::ServiceNewService<F> as actix_net::server::services::InternalServiceFactory>::create::hcb3b03b4a915892e
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/server/services.rs:164
  13:     0x561b4e0bb169 - <alloc::boxed::Box<(dyn actix_net::server::services::InternalServiceFactory + 'static)> as actix_net::server::services::InternalServiceFactory>::create::h15e9fd7ffdfff82b
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/server/services.rs:229
  14:     0x561b4e0ce40d - actix_net::server::worker::Worker::start::h61133df8bb8be014
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/server/worker.rs:147
  15:     0x561b4e0b3a43 - actix_net::server::server::Server::start_worker::{{closure}}::h156fab9d32ccda3f
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-net-0.1.1/src/server/server.rs:254
  16:     0x561b4e0b162a - <F as actix::msgs::FnExec<I, E>>::call_box::h0ab92c5d1d4a1c70
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/msgs.rs:115
  17:     0x561b4e12d54a - <actix::msgs::Execute<I, E>>::exec::h4f51edfd7268690c
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/msgs.rs:99
  18:     0x561b4e14dc46 - <actix::arbiter::Arbiter as actix::handler::Handler<actix::msgs::Execute<I, E>>>::handle::h8cb478689100e640
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/arbiter.rs:266
  19:     0x561b4e140751 - <actix::address::envelope::SyncEnvelopeProxy<A, M> as actix::address::envelope::EnvelopeProxy>::handle::h315b9d9e3d34b3df
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/address/envelope.rs:106
  20:     0x561b4e140588 - <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy>::handle::h55799be4bee3b61e
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/address/envelope.rs:67
  21:     0x561b4e0f981c - <actix::mailbox::Mailbox<A>>::poll::h0bf119563a0f4859
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/mailbox.rs:99
  22:     0x561b4e16232f - <actix::contextimpl::ContextFut<A, C> as futures::future::Future>::poll::he45c117d5584df37
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/contextimpl.rs:346
  23:     0x561b4e15a0d5 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hcb76a27beb3296aa
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  24:     0x561b4e3036c4 - <alloc::boxed::Box<F> as futures::future::Future>::poll::he7f7d0742c04dfa5
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  25:     0x561b4e2ff902 - <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h5b4e1d1b6fe4893a
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  26:     0x561b4e2ffa4f - <futures::task_impl::Spawn<T>>::enter::{{closure}}::h5c667bcba525c676
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  27:     0x561b4e3014cb - futures::task_impl::std::set::hcf9c07ef786bf9ae
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  28:     0x561b4e2ff9ea - <futures::task_impl::Spawn<T>>::enter::h7d732d02f2328443
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  29:     0x561b4e2ff833 - <futures::task_impl::Spawn<T>>::poll_fn_notify::hbb7171179d37627b
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  30:     0x561b4e2ff8d6 - <futures::task_impl::Spawn<T>>::poll_future_notify::h3f8e560bb45661d2
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  31:     0x561b4e30a012 - <tokio_current_thread::scheduler::Scheduled<'a, U>>::tick::hbab3d1c2f20fa117
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/scheduler.rs:354
  32:     0x561b4e309ca2 - <tokio_current_thread::scheduler::Scheduler<U>>::tick::{{closure}}::hee740cf35ba3f502
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/scheduler.rs:333
  33:     0x561b4e307af2 - <tokio_current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}::h8bd94d56180684c3
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:779
  34:     0x561b4e306904 - tokio_current_thread::CurrentRunner::set_spawn::h5c7d698a3fd127c7
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:816
  35:     0x561b4e307a79 - <tokio_current_thread::Borrow<'a, U>>::enter::{{closure}}::hb3b44c3be10c732a
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:778
  36:     0x561b4e2ffffe - <std::thread::local::LocalKey<T>>::try_with::h8fea5a50335b8e90
                        at libstd/thread/local.rs:294
  37:     0x561b4e2ffb26 - <std::thread::local::LocalKey<T>>::with::h5d4aad16cab27f2b
                        at libstd/thread/local.rs:248
  38:     0x561b4e3078ff - <tokio_current_thread::Borrow<'a, U>>::enter::hbf27a736652f50bb
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:776
  39:     0x561b4e309b98 - <tokio_current_thread::scheduler::Scheduler<U>>::tick::hd7e5fa2e559c265d
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/scheduler.rs:333
  40:     0x561b4e307ca1 - <tokio_current_thread::Entered<'a, P>>::tick::h07ceb10d9b809f5f
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:605
  41:     0x561b4e105833 - <tokio_current_thread::Entered<'a, P>>::block_on::h0348025b88d6f877
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:488
  42:     0x561b4e13f7fc - tokio::runtime::current_thread::runtime::Runtime::block_on::{{closure}}::h4cbfc6e4a2965049
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:187
  43:     0x561b4e13f3fc - tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h378130dd15f866d6
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:228
  44:     0x561b4e1373b9 - tokio_executor::global::with_default::{{closure}}::hcba2274b1a092059
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:192
  45:     0x561b4e151bda - <std::thread::local::LocalKey<T>>::try_with::h52eabdc1b8d6b2a5
                        at libstd/thread/local.rs:294
  46:     0x561b4e14f1da - <std::thread::local::LocalKey<T>>::with::h6ddc93f4cc77b1e6
                        at libstd/thread/local.rs:248
  47:     0x561b4e136d63 - tokio_executor::global::with_default::h31bb104a3103209b
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:162
  48:     0x561b4e13f1c5 - tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::h6ad4b57ae52216a0
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:226
  49:     0x561b4e12dfd2 - tokio_timer::timer::handle::with_default::{{closure}}::h3faab420dcbdd4ed
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:94
  50:     0x561b4e152110 - <std::thread::local::LocalKey<T>>::try_with::h58ea134e067e2400
                        at libstd/thread/local.rs:294
  51:     0x561b4e14eafa - <std::thread::local::LocalKey<T>>::with::h01c684a2892cad64
                        at libstd/thread/local.rs:248
  52:     0x561b4e12d750 - tokio_timer::timer::handle::with_default::h9fd5045489e39df2
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:81
  53:     0x561b4e13ef8a - tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::hfc0af25b2a0e91ec
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:219
  54:     0x561b4e157399 - tokio_timer::clock::clock::with_default::{{closure}}::h5c44a6d0a33b1387
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:136
  55:     0x561b4e1549d6 - <std::thread::local::LocalKey<T>>::try_with::hacef04286be61d4c
                        at libstd/thread/local.rs:294
  56:     0x561b4e14ebed - <std::thread::local::LocalKey<T>>::with::h0e5d6e8746fee3a6
                        at libstd/thread/local.rs:248
  57:     0x561b4e156f4f - tokio_timer::clock::clock::with_default::h0e804cd42d1ac8e5
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:119
  58:     0x561b4e13ec4e - tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::h4a7b0b9705fbcd22
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:218
  59:     0x561b4e1227dd - tokio_reactor::with_default::{{closure}}::hfc30c81374988791
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:229
  60:     0x561b4e1523cc - <std::thread::local::LocalKey<T>>::try_with::h5fce8d11ef38d7f6
                        at libstd/thread/local.rs:294
  61:     0x561b4e14f15d - <std::thread::local::LocalKey<T>>::with::h6b2f82c5e7c830b3
                        at libstd/thread/local.rs:248
  62:     0x561b4e121bf3 - tokio_reactor::with_default::h9210fccc947820eb
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:212
  63:     0x561b4e13eb7f - tokio::runtime::current_thread::runtime::Runtime::enter::hf421d6e23f760cef
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:217
  64:     0x561b4e13f786 - tokio::runtime::current_thread::runtime::Runtime::block_on::ha591f9faae3344f0
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:185
  65:     0x561b4e14c3eb - actix::arbiter::Arbiter::new_with_builder::{{closure}}::hc5c6481e96b136cf
                        at /home/diabolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.5/src/arbiter.rs:116
  66:     0x561b4e158196 - std::sys_common::backtrace::__rust_begin_short_backtrace::h00bf811c28aa40e8
                        at libstd/sys_common/backtrace.rs:136
  67:     0x561b4e101774 - std::thread::Builder::spawn::{{closure}}::{{closure}}::hdfb9273fc68e0168
                        at libstd/thread/mod.rs:409
  68:     0x561b4e0f5a54 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc032b94933134d40
                        at libstd/panic.rs:313
  69:     0x561b4e1583a9 - std::panicking::try::do_call::hc84a538a4a33bc72
                        at libstd/panicking.rs:310
  70:     0x561b4e7da129 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  71:     0x561b4e158290 - std::panicking::try::h291aa403818e4363
                        at libstd/panicking.rs:289
  72:     0x561b4e0f74f6 - std::panic::catch_unwind::hd0f0facc715e1fcd
                        at libstd/panic.rs:392
  73:     0x561b4e10155a - std::thread::Builder::spawn::{{closure}}::h9caed0fa8f500360
                        at libstd/thread/mod.rs:408
  74:     0x561b4e103d72 - <F as alloc::boxed::FnBox<A>>::call_box::hfe53c917bf3482dd
                        at liballoc/boxed.rs:646
  75:     0x561b4e7cc6aa - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::hb77935aee02382da
                        at libstd/sys_common/thread.rs:24
  76:     0x561b4e7ba985 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75
                        at libstd/sys/unix/thread.rs:90
  77:     0x7f8f141f46da - start_thread
  78:     0x7f8f13d0588e - __clone
  79:                0x0 - <unknown>', libcore/result.rs:1009:5
```

and that backtrace for other threads

Any idea?

**Comment by diaevd** [comment]
I apologize - this error only occurs when the front has not been statically compiled (public folder not exists)

**Comment by samal84** [comment]
Also to build on linux you need `libpq-dev` as the docs say:

https://github.com/diesel-rs/diesel/blob/master/guide_drafts/backend_installation.md

`sudo apt-get install libpq-dev`

**Comment by krircc** [comment]
yes, when you use postgresql and diesel,  it is need.
